version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
      - 9001:9001
    container_name: mqtt
    hostname: mqtt-server
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    links:
      - parse-server
    depends_on:
      - parse-server
    networks:
      - humi-net
      
  storage:
    image: mongo:4.4.13
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    container_name: storage
    hostname: storage
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${INITDB_ROOT_PASSWORD}"
    networks:
      - humi-net
      
  parse-server:
    build: ./parse_server/.
    command: npm run debug
    environment:
        PARSE_DATABSE_URI: "${DATABASE_URI}"
        PARSE_APP_ID: "${APP_ID}"
        PARSE_MASTER_KEY: "${MASTER_KEY}"
        PARSE_SERVER_URI: "${SERVER_URI}"
        PARSE_APP_URI: "${APP_URI}"
        PARSE_SMTP_PORT: "${SMTP_PORT}"
        PARSE_SMTP_HOST: "${SMTP_HOST}"
        PARSE_SMTP_EMAIL: "${SMTP_EMAIL}"
        PARSE_SMTP_PWD: "${SMTP_PWD}"
    container_name: parse-server
    hostname: parse-server
    ports:
      - 1337:1337
    links:
      - storage
    depends_on:
      - storage
    volumes:
      - ./parse_server:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    networks:
      - humi-net

# Synology fix: https://stackoverflow.com/a/58690946/7110375
networks:
  humi-net:
    name: humi-net
    external: true
    
volumes:
  db_data:
  db_config:
  nodemodules:
