version: "3.9"
services:
  mqtt:
    image: hivemq/hivemq-ce
    ports:
      - "8883:8883"
    volumes:
      - ./hivemq/conf:/opt/hivemq-ce-2021.3/conf
      - ./hivemq/log:/opt/hivemq-ce-2021.3/log
      - ./hivemq/data:/opt/hivemq-ce-2021.3/data
    
  # api:
  #   build:
  #     context: .
  #     dockerfile: docker-api
  #     
  #   ports:
  #     - "443:443"
  #     - "80:443"
  #           
  #   depends_on:
  #     - mqtt
  #     - db
      
  # db:
  